### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by JHLND** [abs-tudelft/sbd#51]
![Screenshot from 2024-09-07 22-03-59](https://github.com/user-attachments/assets/9c1e8c6e-ed87-4d16-850b-7209d81fc1f2)

The part 
> From the [Spark SQL, DataFrames and Datasets Guide](https://spark.apache.org/docs/3.1.2/sql-programming-guide.html#overview)

redirects to a non-existing page

_Edit_:

this is also the case for

> An overview of the different [Spark SQL types](https://spark.apache.org/docs/3.1.2/api/scala/org/apache/spark/sql/types/index.html) can be found online

which is down at the same page.

**Comment by JHLND** [comment]
See also the links of
![Screenshot from 2024-09-07 22-12-06](https://github.com/user-attachments/assets/eedca921-b779-4f7c-8935-125599d53a6f)

**Comment by JHLND** [comment]
- [ ] From the [Spark SQL, DataFrames and Datasets Guide](https://spark.apache.org/docs/3.1.2/sql-programming-guide.html#overview)
- [ ] An overview of the different [Spark SQL types](https://spark.apache.org/docs/3.1.2/api/scala/org/apache/spark/sql/types/index.html) can be found online
- [ ] This was a brief overview of the 2 (or 3) different Spark APIs. You can always find more information on the programming guides for [RDDs](https://spark.apache.org/docs/3.1.2/rdd-programming-guide.html) and [Dataframes/Datasets](https://spark.apache.org/docs/3.1.2/sql-programming-guide.html) and in the [Spark documentation](https://spark.apache.org/docs/3.1.2/api/scala/org/apache/spark/index.html).

**Comment by twoentartian** [comment]
All links are fixed,  reopen this issue if you find more.
